tagline: "Jelajahi proyek saya, baik yang sudah selesai, belum selesai, atau sampah."
lang_name: Indonesia
languages: Bahasa

home: Beranda
categories: Kategori
tags: Tag
archives: Arsip
about: Tentang Saya
